Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7491
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
JSON decode error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6265
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
"GET / HTTP/1.1" 200 6242
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\detection\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: Expecting value: line 1 column 1 (char 0)
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: timed out
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
"GET / HTTP/1.1" 200 6242
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
API data processing error: NetworkTrafficCapture.__init__() missing 1 required positional argument: 'host'
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
"GET / HTTP/1.1" 200 6242
API data processing error: NetworkTrafficCapture.__init__() missing 1 required positional argument: 'host'
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6242
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7475
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6239
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6249
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6471
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6481
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6471
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6471
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6481
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6471
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6481
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
Model loaded successfully!
- Broken pipe from ('127.0.0.1', 60490)
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7707
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6471
"GET /favicon.ico HTTP/1.1" 204 0
API data processing error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
- Broken pipe from ('127.0.0.1', 56547)
API data processing error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6474
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6481
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
Model loaded successfully!
Model loaded successfully!
- Broken pipe from ('127.0.0.1', 56244)
- Broken pipe from ('127.0.0.1', 64569)
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7698
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8555
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9169
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6471
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6481
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7698
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9174
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9187
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
API data processing error: Authentication timeout.
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6475
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 6475
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 75, in start_capture
    if self.capture_active:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'capture_active'
"POST /start_capture/ HTTP/1.1" 500 73731
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 61, in start_capture
    capture = pyshark.LiveCapture(interface="ogstun")
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\live_capture.py", line 47, in __init__
    super(LiveCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                                      eventloop=eventloop, custom_parameters=custom_parameters,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      debug=debug)
                                      ^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
"POST /start_capture/ HTTP/1.1" 500 96101
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9188
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 61, in start_capture
    capture = pyshark.LiveCapture(interface="eth0")
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\live_capture.py", line 47, in __init__
    super(LiveCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                                      eventloop=eventloop, custom_parameters=custom_parameters,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      debug=debug)
                                      ^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
"POST /start_capture/ HTTP/1.1" 500 96091
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 61, in start_capture
    capture = pyshark.LiveCapture(interface="eth0")
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\live_capture.py", line 47, in __init__
    super(LiveCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                                      eventloop=eventloop, custom_parameters=custom_parameters,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      debug=debug)
                                      ^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
"POST /start_capture/ HTTP/1.1" 500 96109
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 61, in start_capture
    capture = pyshark.LiveCapture(interface="eth0")
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\live_capture.py", line 47, in __init__
    super(LiveCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                                      eventloop=eventloop, custom_parameters=custom_parameters,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      debug=debug)
                                      ^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
"POST /start_capture/ HTTP/1.1" 500 96109
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 61, in start_capture
    capture = pyshark.LiveCapture(interface="Wi-Fi")
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\live_capture.py", line 47, in __init__
    super(LiveCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                                      eventloop=eventloop, custom_parameters=custom_parameters,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      debug=debug)
                                      ^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3 (process_request_thread)'.
"POST /start_capture/ HTTP/1.1" 500 96114
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9188
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9188
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 67, in start_capture
    logger.info(capture.summary())
                ^^^^^^^^^^^^^^^
AttributeError: 'LiveCapture' object has no attribute 'summary'
"POST /start_capture/ HTTP/1.1" 500 73998
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 67, in start_capture
    logger.info(capture.summary())
                ^^^^^^^^^^^^^^^
AttributeError: 'LiveCapture' object has no attribute 'summary'
"POST /start_capture/ HTTP/1.1" 500 74036
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
<LiveCapture (54 packets)>
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture started.
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The view app.views.start_capture didn't return an HttpResponse object. It returned None instead.
"POST /start_capture/ HTTP/1.1" 500 74524
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture started.
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6482
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture started.
Packet capture started.
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7712
"GET /favicon.ico HTTP/1.1" 204 0
- Broken pipe from ('127.0.0.1', 57846)
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
Model loaded successfully!
- Broken pipe from ('127.0.0.1', 64192)
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9178
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /start_capture/
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 70, in start_capture
    messages.sucess(request, "Packet capture success.")
    ^^^^^^^^^^^^^^^
AttributeError: module 'django.contrib.messages' has no attribute 'sucess'. Did you mean: 'success'?
"POST /start_capture/ HTTP/1.1" 500 74096
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture success.
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Packet capture success.
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Packet capture success.
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Internal Server Error: /
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 614, in home
    uploaded_file = pyshark.FileCapture('test.pcap')
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\file_capture.py", line 38, in __init__
    super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
                                      include_raw=include_raw, eventloop=eventloop,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      custom_parameters=custom_parameters, debug=debug)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3 (process_request_thread)'.
"POST / HTTP/1.1" 500 97602
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Internal Server Error: /
Traceback (most recent call last):
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py", line 614, in home
    uploaded_file = pyshark.FileCapture('test.pcap')
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\file_capture.py", line 38, in __init__
    super(FileCapture, self).__init__(display_filter=display_filter, only_summaries=only_summaries,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      decryption_key=decryption_key, encryption_type=encryption_type,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
                                      include_raw=include_raw, eventloop=eventloop,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      custom_parameters=custom_parameters, debug=debug)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 88, in __init__
    self._setup_eventloop()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\nakam\Documents\zero-touch-5g-sec-ai\.venv\Lib\site-packages\pyshark\capture\capture.py", line 170, in _setup_eventloop
    current_eventloop = asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Users\nakam\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 716, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
                       % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-3 (process_request_thread)'.
"POST / HTTP/1.1" 500 97602
"GET /favicon.ico HTTP/1.1" 204 0
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Value error: could not convert string to float: 'Benign\r\n{\r\n    "frame.time_relative": -1.909990713'
"POST / HTTP/1.1" 200 9197
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9178
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: cannot access local variable 'obj' where it is not associated with a value
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9178
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [66.0, 60.0, 42.0, 55.0, 55.0, 66.0, 66.0, 42.0, 42.0, 42.0, 42.0, 60.0, 42.0, 42.0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
"POST /start_capture/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
"POST /receive_network_data/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 8562
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [66.0, 60.0, 42.0, 55.0, 55.0, 66.0, 66.0, 42.0, 42.0, 42.0, 42.0, 60.0, 42.0, 42.0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 8562
"GET /favicon.ico HTTP/1.1" 204 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: None
Prediction error: object of type 'NoneType' has no len()
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 2.8722496e-38 0.0000000e+00]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
- Broken pipe from ('127.0.0.1', 54999)
"GET / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 2.8722496e-38 0.0000000e+00]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6783
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7693
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6643
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7693
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7693
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6643
- Broken pipe from ('127.0.0.1', 53202)
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7693
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.909990713, -0.720828222, -0.210455971, 0.17171146, -0.363892373, -0.119927617, -0.125807304, -2.182787826, -0.696464265, -0.212153377, -0.765434182, -0.639727849, -0.843824564, -0.972929059]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[9.9999559e-01 1.2897113e-12 1.7609337e-09 4.4699887e-16 3.2312923e-06
  8.8467896e-12 8.0354721e-07 3.2451860e-16 3.6734525e-07]]
Attack detected: Benign, Severity Level: None, Severity Num: 0
"POST / HTTP/1.1" 200 9178
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [-1.187148031, -0.770073841, -0.210455971, 0.1717114595369835, 2.7480652899506612, -0.119927617, -0.125807304, -1.256617747, -0.559981297, -0.170362847, 1.238213611922419, -0.639727849, 1.1562146768479575, -0.969400906]
Data list length: 14
Data array shape: (1, 1, 14)
Processed data list: [-1.187148031, -0.770073841, -0.210455971, 0.1717114595369835, 2.7480652899506612, -0.119927617, -0.125807304, -1.256617747, -0.559981297, -0.170362847, 1.238213611922419, -0.639727849, 1.1562146768479575, -0.969400906]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[2.1875246e-06 5.6220433e-09 4.8829140e-20 1.8953119e-22 3.8313227e-15
  9.9999785e-01 3.4697297e-13 5.3150620e-24 2.9356869e-13]]
Model prediction: [[2.1875246e-06 5.6220433e-09 4.8829140e-20 1.8953119e-22 3.8313227e-15
  9.9999785e-01 3.4697297e-13 5.3150620e-24 2.9356869e-13]]
Attack detected: SlowrateDoS, Severity Level: Minor, Severity Num: 1
Attack detected: SlowrateDoS, Severity Level: Minor, Severity Num: 1
- Broken pipe from ('127.0.0.1', 55645)
"POST / HTTP/1.1" 200 9218
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: PcapNg: Invalid Block body length (too short)
- Broken pipe from ('127.0.0.1', 63940)
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: slice indices must be integers or None or have an __index__ method
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: slice indices must be integers or None or have an __index__ method
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
Prediction error: slice indices must be integers or None or have an __index__ method
"POST / HTTP/1.1" 200 8559
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7126
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757494102.050035, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
"POST / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757408792.142705, 42, 0, 0, 0, 0, 0, 1, 63, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
- Broken pipe from ('127.0.0.1', 63687)
Error processing data packet: PcapNg: Invalid Block body length (too short)
- Broken pipe from ('127.0.0.1', 54085)
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757408792.142705, 42, 0, 0, 0, 0, 0, 1, 63, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
"POST / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
- Broken pipe from ('127.0.0.1', 57438)
- Broken pipe from ('127.0.0.1', 57643)
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 8558
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 8558
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 8558
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757494348.956082, 42, 0, 0, 0, 0, 0, 17, 63, 0, 0, 8, 1748, 80]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
- Broken pipe from ('127.0.0.1', 58311)
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
- Broken pipe from ('127.0.0.1', 49703)
- Broken pipe from ('127.0.0.1', 54167)
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
- Broken pipe from ('127.0.0.1', 50727)
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Error processing data packet: PcapNg: Invalid Block body length (too short)
- Broken pipe from ('127.0.0.1', 54348)
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757408792.142705, 42, 0, 0, 0, 0, 0, 1, 63, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
- Broken pipe from ('127.0.0.1', 60837)
"GET / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
"POST /stop_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 6652
"GET /favicon.ico HTTP/1.1" 204 0
"GET / HTTP/1.1" 200 6554
"GET /favicon.ico HTTP/1.1" 204 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
- Broken pipe from ('127.0.0.1', 62355)
Error processing data packet: PcapNg: Invalid Block body length (too short)
- Broken pipe from ('127.0.0.1', 64880)
"GET / HTTP/1.1" 200 8616
"GET /favicon.ico HTTP/1.1" 204 0
Processed data list: [1757408792.142705, 42, 0, 0, 0, 0, 0, 1, 63, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
- Broken pipe from ('127.0.0.1', 57394)
"GET / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nakam\Documents\zero-touch-5g-sec-ai\backend\app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 6472
"GET /favicon.ico HTTP/1.1" 204 0
Model loaded successfully!
"POST /start_ml/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 7702
"GET /favicon.ico HTTP/1.1" 204 0
Error processing data packet: PcapNg: Invalid Block body length (too short)
- Broken pipe from ('127.0.0.1', 49880)
Processed data list: [1757408792.142705, 42, 0, 0, 0, 0, 0, 1, 63, 0, 0, 0, 0, 0]
Data list length: 14
Data array shape: (1, 1, 14)
Model prediction: [[4.4136888e-15 1.0000000e+00 3.8134841e-22 1.6053219e-14 2.2480632e-17
  3.7043190e-12 8.2304458e-10 6.1843096e-12 1.7443031e-14]]
Attack detected: HTTPFlood, Severity Level: Minor, Severity Num: 1
"POST / HTTP/1.1" 200 8552
"GET /favicon.ico HTTP/1.1" 204 0
